version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: crylic
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
  messaging:
    image: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      # run `rabbitmq-plugins enable rabbitmq_management` inside the container to use the management interface
      - "15672:15672"
      - "25672:25672"
  graphql-engine:
    image: hasura/graphql-engine:v1.3.2
    ports:
      - "8090:8080"
    depends_on:
      - "db"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://root:admin@db:5432/crylic
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: admin
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"RS256", "jwk_url": "https://crylic.ngrok.io/api/auth/jwks"}'
volumes:
  db_data:
