version: 2.1
parameters:
  workingdir:
    type: string
    default: ~/paint/desktop
orbs:
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@5
  win: circleci/windows@2.2.0
  s3: circleci/aws-s3@3.0
commands:
  setup-windows-node:
    steps:
      - run:
          # specifying --lts doesn't work on windows https://github.com/ampproject/amphtml/issues/17538
          name: Install Node LTS
          command: nvm install 16.13.2
          working_directory: ~/
      - run:
          name: Use Node LTS
          command: nvm use 16.13.2
          working_directory: ~/
      - run:
          name: Install yarn
          command: npm install --global yarn
          working_directory: ~/
  build:
    parameters:
      windows:
        default: false
        type: boolean
    steps:
      - checkout:
          path: ~/paint
      # use the node orb when running on not-windows
      - when:
          condition:
            equal: [false, <<parameters.windows>>]
          steps:
            - node/install-packages:
                app-dir: "<< pipeline.parameters.workingdir >>/app"
                pkg-manager: npm
      # use the windows orb when running on windows
      - when:
          condition:
            equal: [true, <<parameters.windows>>]
          steps:
            - run:
                name: Install app deps
                command: npm i
                working_directory: "<< pipeline.parameters.workingdir >>/app"
      - run:
          name: Install workspace deps
          command: yarn
      - run:
          name: Build desktop
          command: yarn build
      - run:
          name: Package desktop
          command: yarn package
          no_output_timeout: 30m
          environment:
            USE_HARD_LINKS: "false"
      - run:
          name: Create artifacts directory
          command: mkdir /tmp/dist
      - run:
          name: Copy artifacts
          command: mv dist/*.* /tmp/dist
      - run:
          name: Remove extra files
          command: rm /tmp/dist/*.yml
      - store_artifacts:
          path: /tmp/dist
  release:
    steps:
      # Only release to s3 if the build is tagged
      - when:
          condition:
            matches: { pattern: "^v.+$", value: << pipeline.git.tag >> }
          steps:
            - aws-s3/copy:
                from: /tmp/dist
                to: "s3://crylic-artifacts/builds/<< pipeline.git.tag >>"
jobs:
  build-and-release-macos:
    macos:
      xcode: 12.5.1
    resource_class: macos.x86.medium.gen2
    working_directory: << pipeline.parameters.workingdir >>
    steps:
      - build
      - release
  build-and-release-windows:
    executor:
      name: win/default
      shell: powershell.exe
    working_directory: << pipeline.parameters.workingdir >>
    steps:
      - setup-windows-node
      - build:
          windows: true
      - release
workflows:
  release:
    jobs:
      - build-and-release-macos
      - build-and-release-windows
